# Movie Recommendation and Sentiment Analysis

In [1]:
!pip install tmdbv3api
!pip install bs4
!pip install requests

Collecting tmdbv3api
  Downloading tmdbv3api-1.9.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from tmdbv3api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->tmdbv3api) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->tmdbv3api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->tmdbv3api) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->tmdbv3api) (2025.6.15)
Downloading tmdbv3api-1.9.0-py3-none-any.whl (25 kB)
Installing collected packages: tmdbv3api
Successfully installed tmdbv3api-1.9.0
Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from bs4) (4.13.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4) (4.14.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.6.15)

**1. Import Necessary libraries and download NLTK data**

In [2]:
import os
import time
import random
import requests
import pandas as pd
import numpy as np
import joblib
import re

# For model building and similarity calculation
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# For natural language processing (text cleaning)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk

# For web scraping IMDb reviews
from bs4 import BeautifulSoup

# For displaying DataFrames correctly in Jupyter
from IPython.display import display

# Download NLTK data (only needs to be run once)
print("Downloading NLTK stopwords...")
nltk.download('stopwords')
print("Downloading NLTK WordNet...")
nltk.download('wordnet')
print("NLTK downloads complete.")

# how to hide warning
import warnings
warnings.filterwarnings('ignore')

Downloading NLTK stopwords...

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

Downloading NLTK WordNet...
NLTK downloads complete.

**2. Load Pre-trained Models and Set API Key**

In [3]:


# Load pre-trained models and data
print("Loading pre-trained models...")
movies = joblib.load('movies.pkl')
transform_vectorizer = joblib.load('transform.pkl')
svc_model = joblib.load('svc_model.pkl') # trained SVC model for sentiment analysis
print("Models loaded successfully.")

# Set your TMDB API key
tmdb_api_key = os.getenv('TMDB_API_KEY')
if not tmdb_api_key:
    raise ValueError("Error: TMDB_API_KEY is not set. Please set the environment variable or replace the placeholder.")
else:
    print("TMDB API key loaded.")

Loading pre-trained models...
Models loaded successfully.
TMDB API key loaded.

**3. Fetch movie posters and IMDb IDs with TMDB API**

In [4]:
def get_imdb_id(tmdb_id):
    """
    Fetches the IMDb ID for a given TMDB movie ID using the TMDB API.

    Args:
        tmdb_id (int): The The Movie Database (TMDB) ID of the movie.

    Returns:
        str or None: The IMDb ID (e.g., 'tt0468569') if found, otherwise None.
    """
    url = f"https://api.themoviedb.org/3/movie/{tmdb_id}?api_key={tmdb_api_key}&language=en-US"
    try:
        response = requests.get(url)
        response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
        data = response.json()
        return data.get('imdb_id')
    except requests.exceptions.RequestException as e:
        print(f"Error fetching IMDb ID for TMDB ID {tmdb_id}: {e}")
        return None

def fetch_poster(movie_id):
    """
    Fetches the poster URL for a given TMDB movie ID using the TMDB API.

    Args:
        movie_id (int): The The Movie Database (TMDB) ID of the movie.

    Returns:
        str or None: The URL of the movie poster if available, otherwise None.
    """
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={tmdb_api_key}&language=en-US"
    try:
        data = requests.get(url).json()
        poster_path = data.get('poster_path')
        if poster_path:
            return f"https://image.tmdb.org/t/p/w500/{poster_path}"
        return None
    except requests.exceptions.RequestException as e:
        print(f"Error fetching poster for TMDB ID {movie_id}: {e}")
        return None

**4. Text Preprocessing and Sentiment Prediction**

In [5]:
# Cell 4: Text Preprocessing and Sentiment Prediction Functions

def remove_stopwords(text):
    """
    Removes common English stopwords from a given text.

    Args:
        text (str): The input text.

    Returns:
        str: The text with stopwords removed.
    """
    stop_words = stopwords.words('english')
    return ' '.join([word for word in text.split() if word not in stop_words])

def perform_lemmatization(text):
    """
    Performs lemmatization on words in a given text.
    Lemmatization reduces words to their base or root form (e.g., "running" -> "run").

    Args:
        text (str): The input text.

    Returns:
        str: The text with words lemmatized.
    """
    lemmatizer = WordNetLemmatizer()
    return ' '.join([lemmatizer.lemmatize(word) for word in text.split()])

def clean_text(text):
    """
    Cleans a given text by performing the following steps:
    1. Removes HTML tags.
    2. Removes non-alphanumeric characters (keeping spaces).
    3. Removes URLs.
    4. Removes digits.
    5. Converts text to lowercase.
    6. Removes extra whitespace.
    7. Removes stopwords.
    8. Performs lemmatization.

    Args:
        text (str): The raw input text.

    Returns:
        str: The cleaned and processed text.
    """
    text = re.sub(r'<[^>]+>', ' ', text) # Remove HTML tags
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text) # Remove non-alphanumeric characters
    text = re.sub(r'http\S+', '', text) # Remove URLs
    text = re.sub(r'\d+', '', text) # Remove digits
    text = text.lower() # Convert to lowercase
    text = re.sub(r'\s+', ' ', text) # Replace multiple spaces with a single space
    text = remove_stopwords(text) # Remove stopwords
    text = perform_lemmatization(text) # Perform lemmatization
    return text

def predict_sentiment(reviews):
    """
    Predicts the sentiment (Positive/Negative) of a list of movie reviews.

    Args:
        reviews (list of str): A list of raw review strings.

    Returns:
        list of str: A list of predicted sentiments ('Positive' or 'Negative')
                     corresponding to each review. Returns an empty list if no reviews.
    """
    if not reviews:
        return []

    # Clean the review texts
    cleaned = [clean_text(r) for r in reviews]

    # Transform the cleaned texts using the pre-trained vectorizer
    transformed = transform_vectorizer.transform(cleaned)

    # Predict labels using the pre-trained SVC model
    labels = svc_model.predict(transformed)

    # Convert numerical labels (0/1) to 'Negative'/'Positive'
    return ['Positive' if label == 1 else 'Negative' for label in labels]

**5. Scrape IMDB movie reviews**

In [6]:
# Cell 5: IMDb Review Scraper Function

def get_reviews_internal(imdb_movie_id):
    """
    Scrapes movie reviews from IMDb given an IMDb movie ID.
    Includes logic to fetch additional reviews via AJAX 'Load More' buttons.

    Args:
        imdb_movie_id (str): The IMDb ID of the movie (e.g., 'tt0468569').

    Returns:
        list of str: A list of scraped review texts. Returns an empty list if no reviews found
                     or if an error occurs.
    """
    base_imdb_url = "https://www.imdb.com"
    reviews_found = []

    # Define headers to mimic a web browser and avoid being blocked
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

    try:
        if not imdb_movie_id:
            print("Error: No IMDb ID provided to get_reviews_internal. Cannot scrape reviews.")
            return []

        # Construct the URL for the movie's review page
        reviews_url = f"{base_imdb_url}/title/{imdb_movie_id}/reviews"
        print(f"Attempting to scrape reviews from: {reviews_url}")

        # Fetch the initial reviews page
        reviews_response = requests.get(reviews_url, headers=headers)
        reviews_response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
        reviews_soup = BeautifulSoup(reviews_response.text, 'html.parser')

        # Extract reviews from the initial page
        # Look for div elements with data-testid="review-card-parent"
        review_card_parents = reviews_soup.find_all('div', attrs={'data-testid': 'review-card-parent'})

        if not review_card_parents:
            print(f"Warning: No review parent cards found for IMDb ID '{imdb_movie_id}'. "
                  "This might indicate no reviews available or a change in IMDb's HTML structure.")

        for review_parent_div in review_card_parents:
            # Within each review card, find the div containing the actual review text
            review_text_div = review_parent_div.find('div', class_='ipc-html-content-inner-div')
            if review_text_div:
                text = review_text_div.get_text(strip=True) # Get clean text, remove leading/trailing whitespace
                if text:
                    reviews_found.append(text)

        print(f"Found {len(reviews_found)} reviews on initial page.")

        # Handle "Load More" functionality using AJAX
        pagination_key = None
        # Find the container for the "Load More" button
        load_more_container = reviews_soup.find('div', class_='load-more-reviews')
        if load_more_container:
            # Find the button inside this container, which should have the 'data-key' attribute
            load_more_button = load_more_container.find('button', class_='ipc-btn')
            if load_more_button and 'data-key' in load_more_button.attrs:
                pagination_key = load_more_button['data-key']

        # Loop to fetch reviews from subsequent pages via AJAX
        while pagination_key:
            ajax_url = f"{base_imdb_url}/title/{imdb_movie_id}/reviews/_ajax?ref_=undefined&paginationKey={pagination_key}"
            print(f"Fetching more reviews with pagination key: {pagination_key}")

            # Be polite: wait for a random duration to avoid overwhelming the server
            time.sleep(random.uniform(1.5, 3.5))

            ajax_response = requests.get(ajax_url, headers=headers)
            ajax_response.raise_for_status()

            ajax_soup = BeautifulSoup(ajax_response.text, 'html.parser')

            new_review_card_parents = ajax_soup.find_all('div', attrs={'data-testid': 'review-card-parent'})

            # If no new review cards are found, it means there are no more reviews
            if not new_review_card_parents:
                print("No more review pages found.")
                pagination_key = None
                break

            for review_parent_div in new_review_card_parents:
                review_text_div = review_parent_div.find('div', class_='ipc-html-content-inner-div')
                if review_text_div:
                    text = review_text_div.get_text(strip=True)
                    if text:
                        reviews_found.append(text)

            print(f"Total reviews found so far: {len(reviews_found)}")

            # Find the next pagination key from the newly loaded AJAX content
            next_load_more_container = ajax_soup.find('div', class_='load-more-reviews')
            if next_load_more_container:
                next_load_more_button = next_load_more_container.find('button', class_='ipc-btn')
                if next_load_more_button and 'data-key' in next_load_more_button.attrs:
                    pagination_key = next_load_more_button['data-key']
                else:
                    # No data-key found, implying no more pages
                    pagination_key = None
            else:
                # No 'load-more-reviews' container found, implying no more pages
                pagination_key = None

    except requests.exceptions.RequestException as e:
        print(f"Network error or HTTP issue fetching IMDb page for ID {imdb_movie_id}: {e}")
    except Exception as e:
        print(f"An unexpected error occurred during scraping for ID {imdb_movie_id}: {e}")

    return reviews_found

**6. movie recommendations based on a cosine similarity**

In [7]:
# Cell 6: Movie Recommendation Function

def recommend(movie_name):
    """
    Recommends 5 movies similar to the given movie name based on content similarity.

    Args:
        movie_name (str): The title of the movie for which to find recommendations.

    Returns:
        list of tuple: A list of (movie_title, poster_url, tmdb_movie_id) tuples for the
                       top 5 recommended movies. Returns an empty list if the movie
                       is not found in the database.
    """
    if movie_name not in movies['movie_title'].values:
        print(f"Error: Movie '{movie_name}' not found in the recommendation database.")
        return []

    # Get the index of the selected movie
    index = movies[movies['movie_title'] == movie_name].index[0]

    # Re-calculate CountVectorizer and cosine similarity.
    # Note: For efficiency in a larger application, 'vectors' and 'similarity'
    # could be pre-calculated and loaded, rather than re-calculating on each call.
    # However, for this example, re-calculation ensures fresh vectors if 'movies' changes.
    cv = CountVectorizer()
    vectors = cv.fit_transform(movies['comb']) # 'comb' likely represents combined features like genres, cast, crew
    similarity = cosine_similarity(vectors)

    # Get similarity scores for the selected movie with all other movies
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])

    recommendations = []
    # Iterate through the top 5 most similar movies (excluding the movie itself, hence [1:6])
    for i in distances[1:6]:
        tmdb_movie_id = movies.iloc[i[0]].movie_id # Get TMDB ID from your movie dataframe
        poster_url = fetch_poster(tmdb_movie_id) # Fetch poster using the TMDB ID
        title = movies.iloc[i[0]].movie_title
        recommendations.append((title, poster_url, tmdb_movie_id))

    return recommendations

**7. getting recommendations, fetching reviews (using TMDB for IMDb ID), and performing sentiment analysis**

In [8]:
# Cell 7: Main Execution Function

def movie_recommendation_and_sentiments(selected_movie):
    """
    Provides movie recommendations and performs sentiment analysis on reviews
    for a given movie.

    Args:
        selected_movie (str): The title of the movie to process.
    """
    print(f"--- Processing for: {selected_movie} ---")

    # 1. Get TMDB ID for the selected movie from your local 'movies' dataframe
    selected_movie_df = movies[movies['movie_title'] == selected_movie]
    if selected_movie_df.empty:
        print(f"Error: Movie '{selected_movie}' not found in the local movie database. "
              "Cannot provide recommendations or sentiment analysis.")
        return

    selected_tmdb_id = selected_movie_df.iloc[0].movie_id
    print(f"Found TMDB ID: {selected_tmdb_id} for '{selected_movie}'")

    # 2. Use the TMDB ID to get the IMDb ID (via TMDB API)
    imdb_id_for_reviews = get_imdb_id(selected_tmdb_id)
    if imdb_id_for_reviews:
        print(f"Retrieved IMDb ID: {imdb_id_for_reviews} from TMDB.")
    else:
        print(f"Warning: Could not get IMDb ID from TMDB for movie '{selected_movie}'. "
              "Reviews cannot be scraped. Skipping sentiment analysis for this movie.")

    reviews = []
    if imdb_id_for_reviews:
        # 3. Pass the obtained IMDb ID to get_reviews_internal to scrape reviews
        reviews = get_reviews_internal(imdb_id_for_reviews)

    # Display Recommendations
    print(f"\n🎬 Recommendations for: {selected_movie}")
    recommended_movies = recommend(selected_movie)
    if recommended_movies:
        for title, poster, _ in recommended_movies: # Underscore to ignore the TMDB ID returned from recommend
            if poster:
                print(f"{title}\nPoster: {poster}\n")
            else:
                print(f"{title}\nPoster: Not available\n")
    else:
        print("No recommendations found.")

    # Display Sentiment Analysis
    if reviews:
        sentiments = predict_sentiment(reviews)
        df_sentiments = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})
        print("\nSentiment Analysis of Reviews:")

        # Configure Pandas display options for better visibility in Jupyter
        pd.set_option('display.max_rows', None)        # Display all rows
        pd.set_option('display.max_colwidth', None)   # Display full content of columns

        # Use display() for proper, rich HTML table rendering in Jupyter Notebook
        display(df_sentiments)
    else:
        print("❌ No reviews found for sentiment analysis.")

    print(f"--- End of processing for: {selected_movie} ---")

**8. Test recommendations and sentiment of reviews for some movies**

In [9]:
Movie = "The Dark Knight"
movie_recommendation_and_sentiments(Movie)

--- Processing for: The Dark Knight ---
Found TMDB ID: 155.0 for 'The Dark Knight'
Retrieved IMDb ID: tt0468569 from TMDB.
Attempting to scrape reviews from: https://www.imdb.com/title/tt0468569/reviews
Found 18 reviews on initial page.

🎬 Recommendations for: The Dark Knight
The Dark Knight Rises
Poster: https://image.tmdb.org/t/p/w500//hr0L2aueqlP2BYUblTTjmtn0hw4.jpg

Batman Begins
Poster: https://image.tmdb.org/t/p/w500//4MpN4kIEqUjW8OPtOQJXlTdHiJV.jpg

The Prestige
Poster: https://image.tmdb.org/t/p/w500//bdN3gXuIZYaJP7ftKK2sU0nPtEA.jpg

London Has Fallen
Poster: https://image.tmdb.org/t/p/w500//iEbLkYzyiUdOKNK4WNBFyGH7r2Y.jpg

American Psycho
Poster: https://image.tmdb.org/t/p/w500//9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg


Sentiment Analysis of Reviews:

,Review,Sentiment
0,Best movie ever. Heath ledger's work is phenomenal no words......,Positive
1,"This movie is a work of art. The finest sequel ever made. I don't think we will see another movie like this for a long time. Heath Ledger's Joker is the best movie charachter I have ever seen by far. Avengers Endgame is great, but The Dark Knight is much better. The best Batman ever! The best Joker ever! The best DC movie ever! The best superhero movie ever! Ando for me, the best movie ever!",Positive
2,"It is just what you want for the best movie. Great story great acting, thrilling twist.\nJust watched Joker in 2019, I just has to come back and give dark knight a 10. And thanks to Heath Ledger for the exceptional performs.",Positive
3,"Confidently directed, dark, brooding, and packed with impressive action sequences and a complex story, The Dark Knight includes a career-defining turn from Heath Ledger as well as other Oscar worthy performances, TDK remains not only the best Batman movie, but comic book movie ever created.",Positive
4,"We've been subjected to enormous amounts of hype and marketing for the Dark Knight. We've seen Joker scavenger hunts and one of the largest viral campaigns in advertising history and it culminates with the actual release of the movie.Everything that's been said is pretty much spot on. This is the first time I can remember where a summer blockbuster film far surpasses the hype.For as much action as there is in this movie, it's the acting that makes it a great piece of work. Between all the punches, explosions and stunt-work is some great dialog work. All the actors have their moments.Bale's Batman is the definitive Batman because we see everything in this character finally on film. Martial arts skills, cunning, great tactical thinking, forensic application, technological genius to advance or improve Luscious Fox's inventions/technological breakthroughs, intimidating personality, and even a little swashbuckling.As for Heath, yes he gets credit for his performance as the Joker. But you have to also recognize Jonathan and Chris Nolan for the writing and treatment of the character. It's not just the fact that Ledger makes the Joker so menacing, but the Nolans have given the character this great manifesto that drives its actions. The Joker's stance on chaos, order, anarchy, the morality of the average modern human being make the character so interesting psychologically. The Nolans drafted a complex character and only a perfect performance could've pulled something like this off. That's how difficult of a role this was, and that's why Ledger's performance is so great.This isn't an action movie. It's a film that explores literary themes of the hero and villain, as well as order and anarchy. Yes, listen to the dialog because it's all in there.",Positive
5,"I couldn't believe ""The Dark knight"" could live up to the hype. That's perhaps the biggest surprise. The secret, I believe, is a stunning, mature, intelligent script. That makes it the best superhero movie ever made. As if that wasn't enough, Heath Ledger. He, the newest of the tragic modern icons present us with a preview of something we'll never see. A fearless, extraordinary actor capable to fill up with humanity even the most grotesque of villains. His performance is a master class. Fortunately, Christian Bale's Batman is almost a supporting character. Bale is good but there is something around his mouth that stops him from being great. ""The Dark Knight"" is visually stunning, powerful and moving. What else could anyone want.",Positive
6,"Dark, yes, complex, ambitious. Christopher Nolan and his co-writer Jonathan Nolan deserve a standing ovation. I don't usually go for loud movies filled with mindless gore and violence. ""The Dark Knight"" is certainly loud and violent but it's not mindless. It has depth and soul. Even the Joker, in an extraordinary creation by Heath Ledger, is deeply human. The natural petulance of Christian Bale makes his ego and alter ego the most fascinating and complex of all film superheroes. Part of the genius of this movie is that Batman himself, in screen time, is not really the lead. My attention was captivated by Heath Ledger and he determines and inspires the breathtaking atmosphere that envelopes Gotham as well as us. The aplomb of Christopher Nolan as a director is mind blowing and his secret, I believe, is his obvious respect for his audience. What he's done is to elevate a popular genre into Shakesperean proportions. Bravo!",Positive
7,"Im just gonna start off by saying I LOVE this movie.Its one of my favorites of all time. I honestly cant think of too much wrong with this movie other than its a little long and Batmans by now infamous voice. But everything else is top notch. The acting,story,atmosphere,and actions scenes are all amazing. If you haven't seen this movie see it right now! I went into this not expecting to much but I came out blown away, I cant imagine any movie being much better. I'll just have to wait for The Dark Knight Rises to release to see if anything can be better. Until then, this stands as the best movie I've ever seen",Positive
8,"I had the pleasure to watch this movie in an IMAX theatre in London (it advertises itself, with the slogan ""Biggest screen in the UK""), which was one of the greatest movie experiences I had in my life. And it was my first movie in an IMAX theatre. I can only recommend it for anyone who has the chance to watch it, even if not the entire movie is shot for an IMAX theatre, this still is able to blow someone away! Great visuals combined with a great story and superb acting.The movie could also have been called ""The Joker"", but even with Heath Ledgers great performance, this still is a Batman movie. And ""The Dark Knight"" is clear enough, even without the Batman in the title. I simply loved the movie, but I heard some complaints from some friends. It seems that some might have a problem with the depiction of the characters (I loved Heath Ledger, but there are a few out there who would have wanted to see him even crazier) or the plot threads (especially what is done with the character of Aaron Eckhart). Although I can see why that might be a problem for fans of the comic books, I still stand by my vote. This is the best Batman movie ever (until hopefully Nolan and Bale make the next one)!",Positive
9,"Christopher Nolan's second bundle of joy ""The Dark Knight"" EXCEEDED all of my expectations!!! With the success of 2005's reboot of the Batman franchise, they took what was already established and expanded it, amped it up, and gave a deeper, darker and brooding story that is more gripping and the suspense is likely to catch you of guard several times throughout. Christian Bale delves more deeper into Batman, sworn to fight evil and injustice, though also quite reluctant and uncertain if his crusade can ever end and cleanse his inner turmoil from his fractured soul due to the murder of his beloved parents. But with the help of his trusted butler/ally Alfred (played superbly by Michael Cane) grounds him, gives him moral support, and keeps him in check. But the real star of the show is Heath Ledger as Batman's most deadly enemy, The Joker. I can HONESTLY tell you that: as good as Jack Nicholson was in Batman'89 he is CHILD'S PLAY compared to this Joker. He is sadistic, psychotic, and downright SCARIER and PSYCHOLOGICALLY disturbing than the previous incarnation of The Clown Prince of Crime and Ledger gives it his all to do him justice. Along with the original cast comes some fresh faces such as Aaron Eckhart, Maggie Gyllenhaal and more. I must say though I liked Katie Holmes, Gyllenhaal gives a much better performance and is a far cry from the ""damsel-in-distress"" stereotype (though there's a little of it, THANKFULLY) that's common in films. Bale and Gyllenhall have MUCH better chemistry this time around more so than Holmes. Even better, the fight sequences are vastly improved and feature more brutal and bone crushing combat than ""Begins"" in addition to new technology at Batman's disposal. Also worth mentioning is screenwriter Jonathan Nolan, who gives the film an added frosting to an already delicious cake. Simply put, The Dark Knight is totally more bad ass than ""Begins."" The action is great, and the plot is more deeper and engrossing. I applaud Christopher Nolan, Christian Bale, and especially Heath Ledger (who sadly passed away earlier this year) and all those aboard for believing in Mr. Nolan's talents for this second installment. Although some may feel a bit of melancholy over Ledger's death, but as a final note I will say this sincerely from my heart: Remember Heath Ledger and honor him in your minds and hearts not only for his performances, but as a human being and father to his daughter Matilda Ledger. May we issue him best wishes for his family and friends and his daughter for years to come. Remember . . . Honor him not only for this role and past roles, but as an incredible individual and talented actor. Rest in peace. Heath Ledger: 4/4/1979-1/22/2008.",Positive
10,"This film is not the masterpiece that IMDb seems to assign it as. No doubt it's good, especially the tension and the performance of Heath Ledger, but I never saw it as amazing. It's far too long and there are plot holes large enough to drive the school bus through.",Positive
11,"I saw the dark knight about three years ago when I was in the 8th grade. And I was blown away at how beautifully done it was, the camera work, the acting, the story, it all took me by surprise. It is to this day one of the best movies I have ever seen or will see. No other movie can impact you in such an intense way than The Dark Knight. It is a movie worth seeing due to the fact that the workers put so much time and effort into this one film and they did not want to waste money putting up garbage. So Christopher Nolan, thank you for not wasting our time, instead earning our time with this film. To this day I still am anxious to see the movie at home. I recommend it to anyone who likes action movies in general. To anyone who doesn't, don't waste your time write bad reviews about this film.",Positive
12,"If someone else acted as Joker, I would give the movie 7-8 stars. The majority of people ended up loving the villain more than the hero, and that rarely happends in movies.Rest in peace Heath Ledger.",Negative
13,"I used to leave a theatre after seeing a highly anticipated movie, specifically a sequel, and be so revved up about what I saw that I would declare that movie to be the best of a series. After each of the prequel ""Star Wars"" films, I rated that one the best, as good as any of the originals...for a time, until my opinion balanced out and I had a more well-rounded take. For that reason, I steer away from that mindset, and did for ""Dark Knight"".Though my opinion is solidifying already after having seen a Warner Bros. screening last night, ""Dark Knight"" ably stands on its own with or without ""Batman Begins"". At a two and a half hour runtime, it's definitely an epic of a movie, but one that never runs out of gas. A delightful addition to this experience was a healthy amount of IMAX footage, which significantly adds to the feel of being on a personal, and gruesome, tour of Gotham City.Christian Bale plays such a well rounded Batman and Bruce Wayne, qualities that none of those who have donned the cowl before him have pulled off. I still have to remember that Bale is British since he speaks with such a spot on American accent. Bale has a particular slurring lisp that serves him quite well, charmingly for Bruce Wayne and threateningly for Batman.Countering him is the late Heath Ledger, who plays such a scary and creepy Joker that I found it impossible to NOT have chills half the time I saw him on screen. What really separates this brand of Joker from Jack Nicholson's portrayal is true unpredictability. It's obvious that, to be a good guy and think like the Joker, it really takes a toll, and it sure isn't easy. How exactly does one take him down when he's woven his harebrained plot around multiple hostages, explosives, or disappearing parlor tricks?Initially, I was uneasy about how the character of Harvey Dent would be handled. In my mind, there was really only one faithful portrayal of him, and that could be found in the ""Batman"" animated series of the early 90s. As well as Tommy Lee Jones COULD have handled him in ""Batman Forever"", he certainly did not, though it still was a highlight of that movie. Aaron Eckhart ably assumes the mantle here, delivering a performance out of this world, easily on par with the Batman animated series.Be it known, this caped avenger stands for the good of Gotham City that the police force and its counterparts can't represent, the good that has no jurisdiction, no procedures...and no rules, save for one. I can only hope that we've seen just the prelude to the Dark Knight's upcoming legendary battles with the worst of Gotham City's dark underside.""The Dark Knight"" gets a solid 10 of 10 stars.",Positive
14,"I had the honor of watching TDK during a screening and was completely blown away! This isn't just the best Batman movie ever made, this is one of the best movie ever made. Everything in this film is excellent, not one piece of annoyance.Bale marvels as Bruce Wayne/Batman, Ledger has made The Joker in to an iconic movie villain. His performance belongs there at the top with Hopkins Lecter. The Joker has finally been portrait properly on film, he has earned his place between the big boys in movie villandom. This is the true Joker every Batman fan knows, loves and fears. Ledger deserves any and every movie award known to man for this brilliant display.Nolan has made his ""I will always be remembered"" movie, this is the crownjewel in his portfolio. Perfect directing, perfect story, perfect balance between action and drama, everything is perfect.Even if you hate Batman, you will love this film. If you don't, then something beez wrongz with youz!",Positive
15,"*level of enjoyment*\n#10\ntop tier - from start to finish The Dark Knight has you on the edge of your seat, enjoying every minute*likelihood to recommend*\n#10\nhighest recommendation - if you haven't seen it, watch it, it is a masterpiece, the downside? likely to put all future Batman features to shame*quality of acting*\n#9\nexcellent - Bale is the gold standard Batman, gruff, tough, aloof, positively fueled by the tragedies of his dark past. Ledger is the nightmare villain, twisted, evil, unapologetic, irrational, completely void of a moral compass*quality of writing*\n#10\nperfection - one of those movies you wish you could have a memory edit in order to watch again and again*quality of intangibles*\n#8\nexcellent - visual is on point, dark gloomy Gotham, perfect setting for a hero to operate and succeed from the shadows\nvery good - music and sound puts viewers in the mood and anticipating the next intense scene",Positive
16,"Well here it is, one of the most anticipated movies of the year so far. How was it? It was excellent. By far the best Batman film ever made and of course it will be one of the most memorable action films for a long while.Everyone was waiting to see how well Heath Ledger performed as The Joker in this film. He definitely deserves an Oscar in his honor. The character was so dark and creepy that it sent chills up my back. Compared to Heath's other films like '10 Things I Hate About You' and even 'Brokeback Mountain' proves that this man could actually act, doesn't matter what character, he could do it.The film's storyline has many twists and all are rewarding, the story is developed constantly after each scene, making you wonder what's next. Excellent craft and flows well towards the conclusion.During the film on the scene with Batman against the Joker, Bike vs Truck. People thought this was the ending. No, it kept going which was awesome, the story kept getting darker and darker, I guess that's why they called it the 'Dark' Knight as well as the relation to Batman himself.The cast was great. With Christopher Nolan playing Batman, good performance, Heath Ledger played extremely well, Maggie was annoying at times, but still deserves to be praised. Michael Caine and Morgan Freeman had minor roles which satisfied the audiences. Aaron Eckhart starts with a minor role which slowly progresses and becomes evil which is quite surprising and entertaining to watch.Great directing made the movie enjoyable, they added more action this time which made the film feel powerful, lighting was done well especially showing Harvey/ Two Face's face in the many moods he displayed.Great explosions made it entertaining. Made you feel great that this is finally the best action to come in a long time.This movie deserves a 10/10 rating and credit on behalf of the great young actor Heath Ledger's life. (May he R.I.P) His performance made what this film is right now.I recommend this film for any action fan, especially a Batman fan. Or if your even a Heath Ledger fan. Go ahead right now and see this film. It's great!",Positive
17,The dark knight is the best movie I have ever seen in my life,Positive

--- End of processing for: The Dark Knight ---

In [10]:
Movie = "Barbie"
movie_recommendation_and_sentiments(Movie)

--- Processing for: Barbie ---
Found TMDB ID: 346698.0 for 'Barbie'
Retrieved IMDb ID: tt1517268 from TMDB.
Attempting to scrape reviews from: https://www.imdb.com/title/tt1517268/reviews
Found 15 reviews on initial page.

🎬 Recommendations for: Barbie
The Suicide Squad
Poster: https://image.tmdb.org/t/p/w500//q61qEyssk2ku3okWICKArlAdhBn.jpg

The Sisterhood of the Traveling Pants 2
Poster: https://image.tmdb.org/t/p/w500//bAdkVOD91jCHos4163qyVu1TFua.jpg

Babylon
Poster: https://image.tmdb.org/t/p/w500//wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg

Lady Bird
Poster: https://image.tmdb.org/t/p/w500//gl66K7zRdtNYGrxyS2YDUP5ASZd.jpg

I, Tonya
Poster: https://image.tmdb.org/t/p/w500//6gNXwSHxaksR1PjVZRqNapmkgj3.jpg


Sentiment Analysis of Reviews:

,Review,Sentiment
0,"Margot does the best with what she's given, but this film was very disappointing to me. It was marketed as a fun, quirky satire with homages to other movies. It started that way, but ended with over-dramatized speeches and an ending that clearly tried to make the audience feel something, but left everyone just feeling confused. And before you say I'm a crotchety old man, I'm a woman in my 20s, so I'm pretty sure I'm this movie's target audience. The saddest part is there were parents with their kids in the theater that were victims of the poor marketing, because this is not a kid's movie. Overall, the humor was fun on occasion and the film is beautiful to look at, but the whole concept falls apart in the second half of the film and becomes a pity party for the ""strong"" woman.",Negative
1,"I do not usually write reviews, but this is beyond description. Last time I wrote a review it was for the absolutely horrible wrinkle in time. This is almost as bad. At least Gosling plays his part well, but the story is abysmal. If you can find anything else to do like watch paint dry, then yes please do. You will save your brain cells the agony of a painful slow ..... nearly two hours long this was mind-numbing storytelling at its mediocre worst. How many ways can I say do not go see it if you have a choice. See anything else but this exercise in horrendous cliches and exaggerated self-importance. If I could give it negative 10 stars I would.",Negative
2,"Seeing a lot of reviews saying that this movie is preachy, the men are portrayed as idiots, etc. It's a SATIRE. It is meant to be over the top. And yes, it has a lot to say. But the fact that some people in the audience (and I'd wager some of the negative reviews are from people who didn't bother to watch the movie) don't want to hear it, doesn't make it any less valid.In Barbieland, Ken is just an accessory to Barbie and is portrayed as nothing more than an object - something women in the real world deal with all the time. The fact that so many men are reacting so negatively to this movie tells me they don't like being treated the way that women are treated every day. And that is the point of the movie - yet it has much more to say than that. Ultimately, the message in Barbie isn't that ""women rule and men drool"" - it's that patriarchy ultimately harms both men and women. And that's true. So people who say this movie is anti-men are missing the entire point. Patriarchy may give men privilege but it ultimately hurts them, too - pressuring them to conform to a rigid idea of manhood and silencing their self-expression.I am living for the fact that this movie is unapologetic about showing the absurdity of it all. I would have given it a 10 if it weren't for the cringe worthy Ken dance number. It was the only weak part of the movie. But otherwise, Bravo!",Negative
3,"The quality, the humor, and the writing of the movie is fun for a while. It's quirky and it's unique. When they get into the weeds and try to explore deeper themes, the movie is a miss. The middle expositional phase of the movie, I must say, is a bore.The movie was so close to being great, but it was incapable of delivering a message without having a character literally give a speech worth of dialogue.What could have been a great satire and what began as a cleverly funny movie turned into a preachy and moralizing movie in the end. But I guess the charm of the first half of the movie made up for the shortcomings.",Positive
4,"I walked out of the theatre thinking, ""Yeah, I had a good time in that movie"". But as the day went on I kind had that ""Ok, that kebab probably wasn't a good idea.""The film is stunning in its production design and creativity, and Margot Robbie is perfectly cast as the Stereotypical Barbie. For the most part, the songs are catchy and performances are solid for the type of characters being portraying.When we strip away the outside world and all the messaging, Barbie and Ken have a few poignant moments - Barbie realising she's not as perfect as she's been made to believe, or when Ken receives his first modicum of acknowledgement of being a sentient being he's ever had in his life. They also share a couple learning and growth moments which I thought would pay off at the end of the film.I don't know why, but I was hoping for something that would actually enlighten its audience, to acknowledge that things are a mess and make intentional and meaningful steps to get us closer to understanding and equality. The Barbie brand, history, controversies are so engrained in our culture that this movie had a potential to change our perspective of the world, and what the future could be. That's a lot of pressure for one film, I know.However... this film is absolutely not immune to the not-so-subtle messaging that has permeated all forms of media and entertainment recently. In fact, it embraces is. So much so that you have a scene where a man walks up behind Barbie and slaps her on the backside, in broad daylight, in a crowded space, in front of her boyfriend.... And this kind of portrayal of men in 2023 appears to be how the film views the world.Maybe it was this kind of overt comical depiction of men and the world generally that allowed me to get through the movie and kind of enjoy it, but upon reflection, I realise now it's just kind of... yuck.Barbie had the rare opportunity to be a film experience that not only highlighted issues in the real world, but offer and foster some ideas for change. Instead, we receive divisive and mean-spirited attack on half the human population as well as anyone who thinking having a family is an acceptable path in life. And also flat feet and cellulite.If you kind of switch off your brain for an hour and a bit, and don't take this film too seriously, then maybe you'll have a lasting positive memory after seeing this movie.But if you need to do that to enjoy something, then you need to ask yourself: why?",Positive
5,"This is a movie that was way overhyped. Everyone kept saying it was so amazing, but when I finally go to watch it, it was not at all what I thought it was going to be. The storyline was not good. It was a basic and corny storyline, in my opinion.I didn't care for how they portrayed Ken. Ryan Gosling is an amazing actor, but he is not a good representation of Ken when it comes to how he looks and how the actual Ken doll looks. The way he acted as Ken was not that good either, but he didn't get much help from the writers for the way they wrote his part. The movie had so much potential, but was definitely a let down. One positive is that it had some funny parts, but it could of been written much better and could of had a much better storyline!!",Positive
6,"Way too obvious for my taste (or entertainment), Greta Gerwig's ""Barbie"" certainly makes her point about female empowerment, in sledgehammer fashion. Early on, all I could think of were those Captain Obvious TV commercials, amusing in spite of and because of their blatant self-parody.Overproduced as a Hollywood blockbuster hurts a lot, right from the hundredth Kubrick ""2001"" parody to start and then the Busby Berkeley ripoff musical number. And for me, as well as thematically, Ken's character could have usefully been a cameo proportional in screen time to the dozens of supporting Barbie roles -his singing and production number belonged on the cutting room floor.I don't care how many harmless jabs at Mattel were included in the final screenplay, the whole thing is still a marketing ploy.",Negative
7,"It pains me to say it, but I enjoyed this movie so much more then I was expecting to, musical numbers, humour, there truly is something for the whole family yo enjoy.Bright, garish and somewhat kitsch, those were my expectations, and sure it's a veritable cornucopia of glitter and rainbows, but what I wasn't expecting, was for the film to be so engaging, there's actually some real depth that I wasn't expecting. That opening introduction, that came as a major surprise, and pretty much set the tone.Of course there are plenty of double entendres, laughs that adults will enjoy, kids will no doubt chuckle away too.I'm pretty sure this film is going to win awards for its production, it's very well made, creative design and visuals, a lot of thought has gone into this. Greta Gerwig did a great job.Margot Robbie is glorious as Barbie, Ryan Gosling was great I thought. The pair shared some terrific scenes, real chemistry, and plenty of cutting one liners.Great use of music, everything fitted into the film so well.8/10.",Positive
8,"The film's universe and settings are fantastic. The casting is really good too, with Gosling excelling in the role of Ken.Regrettably, however, the film completely misses the chance to appeal to people who grew up with Barbie. Instead, we're left with a film that almost divides and pits men against women, in an attempt to make it a feminist and political film.Instead of seeing a light, fun film, I saw a rather heavy-handed movie whose storyline is centered around patriarchy.It's a real shame, because the film's potential is pretty amazing. I came away disappointed, but not totally disgusted either.",Negative
9,"Wow. I did not see this masterpiece coming. And that's not a joke. Somehow, Greta Gerwig took Barbie, and made a movie that tackles some really tough social issues....well? It's crazy. But wow, does it work. The story is very mature, thinker of a plot. Once you're done laughing your butt off, you'll get really emotional. The production design is so on point. The whole movie is pink everything, but it's never polarizing. All the shades melt together in a very pleasing way. And of course the cast! Margot Robbie was born to play Barbie, and she hits a home run, but Ryan Gosling. This dude rocks as Ken. He knocked it all the way around the world and hit himself in the back of the head. He steals every scene he's in, and I would be so on board with a Ken spin-off. America Ferrara and Simu Liu are also great in their respective roles, but the cast overall is just perfect. Overall, Barbie is probably the best movie based off a toy (sorry LEGO Movies) and an overall fantastic time at the movies.",Positive
10,"Margot Robbie and Ryan Gosling are really great in their roles of Barbie and Kent. Gosling is specially hilarious. I expected a funny, cool, deep and entertaining movie, but I was highly disappointed. The movie is so terribly preachy that ends being an embarrassment. We (the audience) have brains, so, please, preach somewhere else. Furthermore, this is a movie to divide, not to unite. And I'm a woman. The script of the movie is horrendous and the direction is plain bad. There are some great actresses that have too little to say, like Emma Mackey, and that's a pity. Overall: a huge disappointment and a missed opportunity. 3/10 (1 point for Margot Robbie, 1 point for Ryan Gosling, and 1 point for the art direction (super tacky and pinky, as Barbie's world).",Negative
11,"This is very much a movie that will get devided opinions on it, my cousin said well this is two hours of my life i will never get back, and me? I left the theatre in such a good mood. It was the sense of humor for me, laughed so hard. Specially Ryan Gossling was sooooo good and funny, many familiar faces to spot also. And margot robbie come on... the perfect casting for Barbie. I also have to say, the way they created Barbie land was so amazing, it just makes you just want to there. I don't really have anything bad to say about this movie. I can understand not everyone will love it. But i am sure it is a iconic film already.",Positive
12,"While the production value, cinematography and acting were what you would expect from Margo Robbie and the supporting cast. I felt the movie fell short of not preaching to me and spreading a message of division rather than unity. Men and women cannot survive without each other but you'd never know it watching this movie. And me having my 13 year old daughter with me almost caused me to walk out of the theater. I kept on waiting for the writers to hit the direction of unity but it never came. After the movie my daughter brought up the message to me saying how she even noticed the weird agenda they're trying to push and said that is not a movie for the easily impressionable. Come to find out my daughter is better suited to take on the world that I thought she was. Proud day for me as a father.",Negative
13,"Margot Robbie's performance is perfect, and no other actor could've embodied the character as well as she does. However, Ryan Gosling is the film-stealer. I often forget his comedic talent, and he's given a lot of room to flex it in this. A cleverly executed Matchbox Twenty joke is particularly memorable.While cynics and perhaps realists will argue that the film is primarily a marketing vehicle to sell Barbie dolls, it does attempt to carry a moral message. However, the commercial aspect of the movie undercuts the credibility of this message somewhat.The movie starts off well, being smartly self-aware and offering a tongue-in-cheek critique of itself with many winks to the audience. However, as it progresses, the commentary on feminism and the patriarchy becomes heavy-handed, especially in the dialogue-heavy third act, which weighs down the overall narrative.The set and wardrobe designs are a standout. I think kids will love this part alone, even if some of the humor and social commentary will go over their heads.Overall, it's a fun film but not without its flaws. It's likely to spark discussion due to its blunt societal commentary. If you're looking for a visually impressive movie to entertain the kids, and you're willing to enjoy it without analyzing its message too deeply, then it's an enjoyable watch.",Positive
14,"8.5/10\nWhile i'm not so sure at first, the movie kept getting even more fun, entertaining, and definitely better, also surprisingly deal with a legit serious stuff, Barbie is a weirdly fun movie that fills with this very interesting concept, definitely the first time that's ever done, Greta Gerwig has created this whole new style of filmmaking specifically for Barbie, from the intentionally weird yet creative editing, some awkward and cringe scene, i found the comedy so funny instead of cringe, Barbie is one of the most original movie of the year and also one of the most original movie i've seen in a while, we all know Margot Robbie and Ryan Gosling is gonna carry the movie and they are, but Will Ferrell, Simu Liu, and the whole rest of the cast were also great and entertaining, the soundtrack was just great, except Nicki Minaj and Ice Spice ""Barbie World"" song that are just absolutely terrible, but Billie Eilish ""What Was I Made For?"" tune that kept haunting in the background until it finally get the perfect scene to played it was really the best thing because that song was just beautiful and emotional, anyway, Barbie is a lot of fun, while there is still some noticeable flawed, most of them i found it funny, entertaining, colourful, creative, and fun, pure fun, it's something that i probably will love it even more the second time i see it, but as of right now, Barbie was a good time, definitely recommended and with this movie somehow it's actually possible to have a live-action Barbie movie, all you need to have is a good writer, good director, and good cast, and they delivers mostly.",Positive

--- End of processing for: Barbie ---

In [11]:
import os
import time
import random
import requests
import pandas as pd
import numpy as np
import joblib
import re

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk

from bs4 import BeautifulSoup

nltk.download('stopwords')
nltk.download('wordnet')


movies = joblib.load('movies.pkl')
transform_vectorizer = joblib.load('transform.pkl')
svc_model = joblib.load('svc_model.pkl')

tmdb_api_key = '613b9e66c1e1b3fee798437e9803e1b5'
if not tmdb_api_key:
    raise ValueError("Please set the TMDB_API_KEY environment variable.")

# This function is correct as is, it fetches IMDb ID using TMDB movie ID
def get_imdb_id(tmdb_id):
    url = f"https://api.themoviedb.org/3/movie/{tmdb_id}?api_key={tmdb_api_key}&language=en-US"
    response = requests.get(url)
    data = response.json()
    return data.get('imdb_id')

def fetch_poster(movie_id):
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={tmdb_api_key}&language=en-US"
    data = requests.get(url).json()
    poster_path = data.get('poster_path')
    if poster_path:
        return f"https://image.tmdb.org/t/p/w500/{poster_path}"
    return None

def remove_stopwords(text):
    stop_words = stopwords.words('english')
    return ' '.join([word for word in text.split() if word not in stop_words])

def perform_lemmatization(text):
    lemmatizer = WordNetLemmatizer()
    return ' '.join([lemmatizer.lemmatize(word) for word in text.split()])

def clean_text(text):
    text = re.sub(r'<[^>]+>', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'\d+', '', text)
    text = text.lower()
    text = re.sub(r'\s+', ' ', text)
    text = remove_stopwords(text)
    text = perform_lemmatization(text)
    return text

def predict_sentiment(reviews):
    if not reviews:
        return []
    cleaned = [clean_text(r) for r in reviews]
    transformed = transform_vectorizer.transform(cleaned)
    labels = svc_model.predict(transformed)
    return ['Positive' if label == 1 else 'Negative' for label in labels]

def get_reviews_internal(imdb_movie_id): # This function now expects an IMDb ID
    base_imdb_url = "https://www.imdb.com"
    reviews_found = []

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

    try:
        # Step 1 (Skipped): We already have the IMDb ID, no need to search IMDb for it.
        # This function now assumes a valid IMDb ID is passed to it.
        if not imdb_movie_id:
            print("No IMDb ID provided to get_reviews_internal.")
            return []

        # Construct the URL for the movie's review page using the provided IMDb ID
        reviews_url = f"{base_imdb_url}/title/{imdb_movie_id}/reviews"

        # Step 2: Fetch the reviews page
        reviews_response = requests.get(reviews_url, headers=headers)
        reviews_response.raise_for_status()
        reviews_soup = BeautifulSoup(reviews_response.text, 'html.parser')

        # Step 3: Extract reviews using the provided HTML structure
        review_card_parents = reviews_soup.find_all('div', attrs={'data-testid': 'review-card-parent'})

        if not review_card_parents:
            print(f"No review parent cards found for IMDb ID '{imdb_movie_id}' at {reviews_url}. This might indicate no reviews or a change in the review page HTML structure.")

        for review_parent_div in review_card_parents:
            review_text_div = review_parent_div.find('div', class_='ipc-html-content-inner-div')
            if review_text_div:
                text = review_text_div.get_text(strip=True)
                if text:
                    reviews_found.append(text)

        # Handle "Load More" (AJAX)
        pagination_key = None
        load_more_container = reviews_soup.find('div', class_='load-more-reviews')
        if load_more_container:
            load_more_button = load_more_container.find('button', class_='ipc-btn')
            if load_more_button and 'data-key' in load_more_button.attrs:
                pagination_key = load_more_button['data-key']

        while pagination_key:
            ajax_url = f"{base_imdb_url}/title/{imdb_movie_id}/reviews/_ajax?ref_=undefined&paginationKey={pagination_key}"

            time.sleep(random.uniform(1.5, 3.5))

            ajax_response = requests.get(ajax_url, headers=headers)
            ajax_response.raise_for_status()

            ajax_soup = BeautifulSoup(ajax_response.text, 'html.parser')

            new_review_card_parents = ajax_soup.find_all('div', attrs={'data-testid': 'review-card-parent'})

            if not new_review_card_parents:
                pagination_key = None
                break

            for review_parent_div in new_review_card_parents:
                review_text_div = review_parent_div.find('div', class_='ipc-html-content-inner-div')
                if review_text_div:
                    text = review_text_div.get_text(strip=True)
                    if text:
                        reviews_found.append(text)

            next_load_more_container = ajax_soup.find('div', class_='load-more-reviews')
            if next_load_more_container:
                next_load_more_button = next_load_more_container.find('button', class_='ipc-btn')
                if next_load_more_button and 'data-key' in next_load_more_button.attrs:
                    pagination_key = next_load_more_button['data-key']
                else:
                    pagination_key = None
            else:
                pagination_key = None

    except requests.exceptions.RequestException as e:
        print(f"Network error or HTTP issue fetching IMDb page for ID {imdb_movie_id}: {e}")
    except Exception as e:
        print(f"An unexpected error occurred during scraping for ID {imdb_movie_id}: {e}")

    return reviews_found


def recommend(movie_name):
    if movie_name not in movies['movie_title'].values:
        print(f"Movie '{movie_name}' not found in the database.")
        return []

    index = movies[movies['movie_title'] == movie_name].index[0]

    cv = CountVectorizer()
    vectors = cv.fit_transform(movies['comb'])
    similarity = cosine_similarity(vectors)

    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])

    recommendations = []
    for i in distances[1:6]:
        # --- IMPORTANT CHANGE HERE: Store TMDB ID to use get_imdb_id later ---
        tmdb_movie_id = movies.iloc[i[0]].movie_id # Assuming 'movie_id' in movies.pkl is TMDB ID
        poster_url = fetch_poster(tmdb_movie_id) # Use TMDB ID for poster
        title = movies.iloc[i[0]].movie_title
        recommendations.append((title, poster_url, tmdb_movie_id)) # Add tmdb_movie_id to recommendations
    return recommendations

def movie_recommendation_and_sentiments(selected_movie):
    # 1. Get TMDB ID for the selected movie from your local 'movies' dataframe
    # This assumes 'movies.pkl' contains both movie_title and TMDB movie_id
    selected_movie_df = movies[movies['movie_title'] == selected_movie]
    if selected_movie_df.empty:
        print(f"Movie '{selected_movie}' not found in the local database for sentiment analysis.")
        return

    # Get the TMDB ID for the selected_movie
    selected_tmdb_id = selected_movie_df.iloc[0].movie_id

    # 2. Use the TMDB ID to get the IMDb ID
    imdb_id_for_reviews = get_imdb_id(selected_tmdb_id)

    reviews = []
    if imdb_id_for_reviews:
        # 3. Pass the obtained IMDb ID to get_reviews_internal
        reviews = get_reviews_internal(imdb_id_for_reviews)
    else:
        print(f"Could not get IMDb ID from TMDB for movie '{selected_movie}'. Skipping review scraping.")


    print(f"\n🎬 Recommendations for: {selected_movie}")
    # The 'recommend' function now returns TMDB IDs, which is good.
    # We still want to use the TMDB ID for fetching posters for recommendations.
    for title, poster, _ in recommend(selected_movie): # _ to ignore the TMDB ID from recommend for display
        if poster:
            print(f"{title}\nPoster: {poster}\n")
        else:
            print(f"{title}\nPoster: Not available\n")

    if reviews:
        sentiments = predict_sentiment(reviews)
        df_sentiments = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})
        print("\nSentiment Analysis of Reviews:")
        pd.set_option('display.max_rows', None)
        pd.set_option('display.max_colwidth', None)
        display(df_sentiments)

    else:
        print("❌ No reviews found for sentiment analysis.")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [12]:
# Call the main function
movie_recommendation_and_sentiments('Pirates of the Caribbean: The Curse of the Black Pearl')

🎬 Recommendations for: Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: At World's End
Poster: https://image.tmdb.org/t/p/w500//jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg

Pirates of the Caribbean: Dead Man's Chest
Poster: https://image.tmdb.org/t/p/w500//lAhcKRt0ggTFkeFL95jrGQYaRXs.jpg

Pirates of the Caribbean: Dead Men Tell No Tales
Poster: https://image.tmdb.org/t/p/w500//qwoGfcg6YUS55nUweKGujHE54Wy.jpg

The Lone Ranger
Poster: https://image.tmdb.org/t/p/w500//xRmsqvHnaWmrazJl9bTBqs4LAjp.jpg

Pirates of the Caribbean: On Stranger Tides
Poster: https://image.tmdb.org/t/p/w500//keGfSvCmYj7CvdRx36OdVrAEibE.jpg


Sentiment Analysis of Reviews:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Review  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           You will always remember this as the movie that made Johnny Depp a superstar and almost got him an Oscar.The fact that he didn't win isn't a problem,since thanks to him this is the best pirate film ever made.The opening concept is a clichè:a beautiful woman(Keira Knightley)is kidnapped by a bunch of filthy pirates(led by Geoffrey Rush's Barbossa)and the man(Orlando Bloom)who's desperately in love with her decides to track them down.From now on,things get unexpected,as he asks another pirate for help.And it's no ordinary pirate:it's Captain Jack Sparrow(Johnny Depp),a lying,cheating,but charismatic scumbag,the hardest man on Earth to predict,not to mention quite unlucky and clumsy("You are,with no doubt,the worst pirate I've ever heard of" "But you HAVE heard of me!").It's got all the elements of a classic pirate movie,elements that would give this flick a 9/10.So,why am I giving it a 10/10? The answer is simple:Captain Jack.From the moment he makes his entrance,justly included in the Empire Top 10 Entrances of all time,we know he's the reason people will keep watching the movie.He 's Depp's best non-Tim Burton-character ever,and I can't wait 'til he returns.See you next summer,Captain!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Although I had expectations ( from watching the trailers ) that this might be a good movie, I was still surprised that it's as good as it is. The story is actually more complex than I had expected, involving cursed pirates and their quest to rid themselves of the curse. I won't say more than that so as not to spoil it if you haven't seen it.There aren't as many action scenes as I had thought there would be in a pirate movie, but the ones that are in the movie were very fun and enjoyable. After seeing it, I think it had the right balance of action and drama. There are also, of course, a lot of funny bits interspersed between the action and drama. Some really good special effects also add to the enjoyment of this movie.I wasn't much of a fan of Johnny Depp until I saw this movie. I think he deserved to win the Academy Award for best actor. It's largely because of his performance, IMO, that the movie was so good. Most of the supporting cast did well, mind you, just that Johnny Depp stood high above the rest. I did find Orlando Bloom's performance a bit wooden, but other than that the acting was good.Basically, it's a really fun movie and I'd give it about 8 out of 10

In [13]:
movie_recommendation_and_sentiments('Barbie')

🎬 Recommendations for: Barbie
The Suicide Squad
Poster: https://image.tmdb.org/t/p/w500//q61qEyssk2ku3okWICKArlAdhBn.jpg

The Sisterhood of the Traveling Pants 2
Poster: https://image.tmdb.org/t/p/w500//bAdkVOD91jCHos4163qyVu1TFua.jpg

Babylon
Poster: https://image.tmdb.org/t/p/w500//wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg

Lady Bird
Poster: https://image.tmdb.org/t/p/w500//gl66K7zRdtNYGrxyS2YDUP5ASZd.jpg

I, Tonya
Poster: https://image.tmdb.org/t/p/w500//6gNXwSHxaksR1PjVZRqNapmkgj3.jpg


Sentiment Analysis of Reviews:

,Review,Sentiment
0,"Margot does the best with what she's given, but this film was very disappointing to me. It was marketed as a fun, quirky satire with homages to other movies. It started that way, but ended with over-dramatized speeches and an ending that clearly tried to make the audience feel something, but left everyone just feeling confused. And before you say I'm a crotchety old man, I'm a woman in my 20s, so I'm pretty sure I'm this movie's target audience. The saddest part is there were parents with their kids in the theater that were victims of the poor marketing, because this is not a kid's movie. Overall, the humor was fun on occasion and the film is beautiful to look at, but the whole concept falls apart in the second half of the film and becomes a pity party for the ""strong"" woman.",Negative
1,"I do not usually write reviews, but this is beyond description. Last time I wrote a review it was for the absolutely horrible wrinkle in time. This is almost as bad. At least Gosling plays his part well, but the story is abysmal. If you can find anything else to do like watch paint dry, then yes please do. You will save your brain cells the agony of a painful slow ..... nearly two hours long this was mind-numbing storytelling at its mediocre worst. How many ways can I say do not go see it if you have a choice. See anything else but this exercise in horrendous cliches and exaggerated self-importance. If I could give it negative 10 stars I would.",Negative
2,"Seeing a lot of reviews saying that this movie is preachy, the men are portrayed as idiots, etc. It's a SATIRE. It is meant to be over the top. And yes, it has a lot to say. But the fact that some people in the audience (and I'd wager some of the negative reviews are from people who didn't bother to watch the movie) don't want to hear it, doesn't make it any less valid.In Barbieland, Ken is just an accessory to Barbie and is portrayed as nothing more than an object - something women in the real world deal with all the time. The fact that so many men are reacting so negatively to this movie tells me they don't like being treated the way that women are treated every day. And that is the point of the movie - yet it has much more to say than that. Ultimately, the message in Barbie isn't that ""women rule and men drool"" - it's that patriarchy ultimately harms both men and women. And that's true. So people who say this movie is anti-men are missing the entire point. Patriarchy may give men privilege but it ultimately hurts them, too - pressuring them to conform to a rigid idea of manhood and silencing their self-expression.I am living for the fact that this movie is unapologetic about showing the absurdity of it all. I would have given it a 10 if it weren't for the cringe worthy Ken dance number. It was the only weak part of the movie. But otherwise, Bravo!",Negative
3,"The quality, the humor, and the writing of the movie is fun for a while. It's quirky and it's unique. When they get into the weeds and try to explore deeper themes, the movie is a miss. The middle expositional phase of the movie, I must say, is a bore.The movie was so close to being great, but it was incapable of delivering a message without having a character literally give a speech worth of dialogue.What could have been a great satire and what began as a cleverly funny movie turned into a preachy and moralizing movie in the end. But I guess the charm of the first half of the movie made up for the shortcomings.",Positive
4,"I walked out of the theatre thinking, ""Yeah, I had a good time in that movie"". But as the day went on I kind had that ""Ok, that kebab probably wasn't a good idea.""The film is stunning in its production design and creativity, and Margot Robbie is perfectly cast as the Stereotypical Barbie. For the most part, the songs are catchy and performances are solid for the type of characters being portraying.When we strip away the outside world and all the messaging, Barbie and Ken have a few poignant moments - Barbie realising she's not as perfect as she's been made to believe, or when Ken receives his first modicum of acknowledgement of being a sentient being he's ever had in his life. They also share a couple learning and growth moments which I thought would pay off at the end of the film.I don't know why, but I was hoping for something that would actually enlighten its audience, to acknowledge that things are a mess and make intentional and meaningful steps to get us closer to understanding and equality. The Barbie brand, history, controversies are so engrained in our culture that this movie had a potential to change our perspective of the world, and what the future could be. That's a lot of pressure for one film, I know.However... this film is absolutely not immune to the not-so-subtle messaging that has permeated all forms of media and entertainment recently. In fact, it embraces is. So much so that you have a scene where a man walks up behind Barbie and slaps her on the backside, in broad daylight, in a crowded space, in front of her boyfriend.... And this kind of portrayal of men in 2023 appears to be how the film views the world.Maybe it was this kind of overt comical depiction of men and the world generally that allowed me to get through the movie and kind of enjoy it, but upon reflection, I realise now it's just kind of... yuck.Barbie had the rare opportunity to be a film experience that not only highlighted issues in the real world, but offer and foster some ideas for change. Instead, we receive divisive and mean-spirited attack on half the human population as well as anyone who thinking having a family is an acceptable path in life. And also flat feet and cellulite.If you kind of switch off your brain for an hour and a bit, and don't take this film too seriously, then maybe you'll have a lasting positive memory after seeing this movie.But if you need to do that to enjoy something, then you need to ask yourself: why?",Positive
5,"This is a movie that was way overhyped. Everyone kept saying it was so amazing, but when I finally go to watch it, it was not at all what I thought it was going to be. The storyline was not good. It was a basic and corny storyline, in my opinion.I didn't care for how they portrayed Ken. Ryan Gosling is an amazing actor, but he is not a good representation of Ken when it comes to how he looks and how the actual Ken doll looks. The way he acted as Ken was not that good either, but he didn't get much help from the writers for the way they wrote his part. The movie had so much potential, but was definitely a let down. One positive is that it had some funny parts, but it could of been written much better and could of had a much better storyline!!",Positive
6,"Way too obvious for my taste (or entertainment), Greta Gerwig's ""Barbie"" certainly makes her point about female empowerment, in sledgehammer fashion. Early on, all I could think of were those Captain Obvious TV commercials, amusing in spite of and because of their blatant self-parody.Overproduced as a Hollywood blockbuster hurts a lot, right from the hundredth Kubrick ""2001"" parody to start and then the Busby Berkeley ripoff musical number. And for me, as well as thematically, Ken's character could have usefully been a cameo proportional in screen time to the dozens of supporting Barbie roles -his singing and production number belonged on the cutting room floor.I don't care how many harmless jabs at Mattel were included in the final screenplay, the whole thing is still a marketing ploy.",Negative
7,"It pains me to say it, but I enjoyed this movie so much more then I was expecting to, musical numbers, humour, there truly is something for the whole family yo enjoy.Bright, garish and somewhat kitsch, those were my expectations, and sure it's a veritable cornucopia of glitter and rainbows, but what I wasn't expecting, was for the film to be so engaging, there's actually some real depth that I wasn't expecting. That opening introduction, that came as a major surprise, and pretty much set the tone.Of course there are plenty of double entendres, laughs that adults will enjoy, kids will no doubt chuckle away too.I'm pretty sure this film is going to win awards for its production, it's very well made, creative design and visuals, a lot of thought has gone into this. Greta Gerwig did a great job.Margot Robbie is glorious as Barbie, Ryan Gosling was great I thought. The pair shared some terrific scenes, real chemistry, and plenty of cutting one liners.Great use of music, everything fitted into the film so well.8/10.",Positive
8,"The film's universe and settings are fantastic. The casting is really good too, with Gosling excelling in the role of Ken.Regrettably, however, the film completely misses the chance to appeal to people who grew up with Barbie. Instead, we're left with a film that almost divides and pits men against women, in an attempt to make it a feminist and political film.Instead of seeing a light, fun film, I saw a rather heavy-handed movie whose storyline is centered around patriarchy.It's a real shame, because the film's potential is pretty amazing. I came away disappointed, but not totally disgusted either.",Negative
9,"Wow. I did not see this masterpiece coming. And that's not a joke. Somehow, Greta Gerwig took Barbie, and made a movie that tackles some really tough social issues....well? It's crazy. But wow, does it work. The story is very mature, thinker of a plot. Once you're done laughing your butt off, you'll get really emotional. The production design is so on point. The whole movie is pink everything, but it's never polarizing. All the shades melt together in a very pleasing way. And of course the cast! Margot Robbie was born to play Barbie, and she hits a home run, but Ryan Gosling. This dude rocks as Ken. He knocked it all the way around the world and hit himself in the back of the head. He steals every scene he's in, and I would be so on board with a Ken spin-off. America Ferrara and Simu Liu are also great in their respective roles, but the cast overall is just perfect. Overall, Barbie is probably the best movie based off a toy (sorry LEGO Movies) and an overall fantastic time at the movies.",Positive
10,"Margot Robbie and Ryan Gosling are really great in their roles of Barbie and Kent. Gosling is specially hilarious. I expected a funny, cool, deep and entertaining movie, but I was highly disappointed. The movie is so terribly preachy that ends being an embarrassment. We (the audience) have brains, so, please, preach somewhere else. Furthermore, this is a movie to divide, not to unite. And I'm a woman. The script of the movie is horrendous and the direction is plain bad. There are some great actresses that have too little to say, like Emma Mackey, and that's a pity. Overall: a huge disappointment and a missed opportunity. 3/10 (1 point for Margot Robbie, 1 point for Ryan Gosling, and 1 point for the art direction (super tacky and pinky, as Barbie's world).",Negative
11,"This is very much a movie that will get devided opinions on it, my cousin said well this is two hours of my life i will never get back, and me? I left the theatre in such a good mood. It was the sense of humor for me, laughed so hard. Specially Ryan Gossling was sooooo good and funny, many familiar faces to spot also. And margot robbie come on... the perfect casting for Barbie. I also have to say, the way they created Barbie land was so amazing, it just makes you just want to there. I don't really have anything bad to say about this movie. I can understand not everyone will love it. But i am sure it is a iconic film already.",Positive
12,"While the production value, cinematography and acting were what you would expect from Margo Robbie and the supporting cast. I felt the movie fell short of not preaching to me and spreading a message of division rather than unity. Men and women cannot survive without each other but you'd never know it watching this movie. And me having my 13 year old daughter with me almost caused me to walk out of the theater. I kept on waiting for the writers to hit the direction of unity but it never came. After the movie my daughter brought up the message to me saying how she even noticed the weird agenda they're trying to push and said that is not a movie for the easily impressionable. Come to find out my daughter is better suited to take on the world that I thought she was. Proud day for me as a father.",Negative
13,"Margot Robbie's performance is perfect, and no other actor could've embodied the character as well as she does. However, Ryan Gosling is the film-stealer. I often forget his comedic talent, and he's given a lot of room to flex it in this. A cleverly executed Matchbox Twenty joke is particularly memorable.While cynics and perhaps realists will argue that the film is primarily a marketing vehicle to sell Barbie dolls, it does attempt to carry a moral message. However, the commercial aspect of the movie undercuts the credibility of this message somewhat.The movie starts off well, being smartly self-aware and offering a tongue-in-cheek critique of itself with many winks to the audience. However, as it progresses, the commentary on feminism and the patriarchy becomes heavy-handed, especially in the dialogue-heavy third act, which weighs down the overall narrative.The set and wardrobe designs are a standout. I think kids will love this part alone, even if some of the humor and social commentary will go over their heads.Overall, it's a fun film but not without its flaws. It's likely to spark discussion due to its blunt societal commentary. If you're looking for a visually impressive movie to entertain the kids, and you're willing to enjoy it without analyzing its message too deeply, then it's an enjoyable watch.",Positive
14,"8.5/10\nWhile i'm not so sure at first, the movie kept getting even more fun, entertaining, and definitely better, also surprisingly deal with a legit serious stuff, Barbie is a weirdly fun movie that fills with this very interesting concept, definitely the first time that's ever done, Greta Gerwig has created this whole new style of filmmaking specifically for Barbie, from the intentionally weird yet creative editing, some awkward and cringe scene, i found the comedy so funny instead of cringe, Barbie is one of the most original movie of the year and also one of the most original movie i've seen in a while, we all know Margot Robbie and Ryan Gosling is gonna carry the movie and they are, but Will Ferrell, Simu Liu, and the whole rest of the cast were also great and entertaining, the soundtrack was just great, except Nicki Minaj and Ice Spice ""Barbie World"" song that are just absolutely terrible, but Billie Eilish ""What Was I Made For?"" tune that kept haunting in the background until it finally get the perfect scene to played it was really the best thing because that song was just beautiful and emotional, anyway, Barbie is a lot of fun, while there is still some noticeable flawed, most of them i found it funny, entertaining, colourful, creative, and fun, pure fun, it's something that i probably will love it even more the second time i see it, but as of right now, Barbie was a good time, definitely recommended and with this movie somehow it's actually possible to have a live-action Barbie movie, all you need to have is a good writer, good director, and good cast, and they delivers mostly.",Positive